---
- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: Configure HAProxy
  copy:
    dest: /etc/haproxy/haproxy.cfg
    content: |
      global
          daemon
          maxconn 256

      defaults
          mode http
          timeout connect 5000ms
          timeout client 50000ms
          timeout server 50000ms

      frontend http_front
          bind *:80
          default_backend web_back

      backend web_back
          balance roundrobin
          server web1 192.168.100.21:80 check
          server web2 192.168.100.22:80 check
          
- name: Open HTTP port in firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Reload firewalld
  command: firewall-cmd --reload
  when: ansible_facts['os_family'] == 'RedHat'

- name: Start and enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
