---
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Enable and start Apache
  service:
    name: httpd
    state: started
    enabled: true

- name: Open HTTP port in firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Reload firewalld
  command: firewall-cmd --reload
  when: ansible_facts['os_family'] == 'RedHat'

- name: Create index page
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello from {{ node_role }}</h1>"
